### PR TITLE
Added argparser support

### PR DESCRIPTION
**Pull request by ezhil56x**
## Description 
- Added support for `--host` and `--port` through argparser
- Added required packages to poetry

/claim #141

### CODE REVIEW

**Comment by ezhil56x** [comment]
Any update?

**Comment by ajhai** [comment]
@ezhil56x thanks for the PR. Can you confirm that the changes work? Expectation is that the user can start llmstack on a different host and port. So when I give `--host`, it should use that to run django server. Same with port. Django should run on the specified port.

**Comment by ezhil56x** [comment]
Yeah when `--port` and `--host` are used it will be used else it will be loaded from config. Can you check once from your side?

**Comment by ezhil56x** [comment]
If it's not working as expected, will make the required changes

**Comment by ezhil56x** [comment]
@ajhai Any update?

**Comment by ajhai** [comment]
We decided to go with @TakshPanchal's PR who claimed this before and submitted a working diff. Thanks for sending this PR.

**Pull request closed without merging**
